[package]
name = "tw_keypair"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
k256 = { version = "0.13.0", features = ["ecdh"] }
starknet-crypto = "0.4.3"
starknet-ff = "0.3.1"
tw_encoding = { path = "../tw_encoding" }
tw_hash = { path = "../tw_hash" }
tw_memory = { path = "../tw_memory" }
tw_utils = { path = "../tw_utils" }
