name: Codegen-v2 Tests

on:
  push:
    branches:
      - master
    paths:
      - 'codegen-v2/**'
  pull_request:
    branches:
      - master
    paths:
      - 'codegen-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: test
